name: Python Enterprise CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  # --- THE CI PART (Test the code) ---
  test-code:
    runs-on: ubuntu-latest
    steps:
    - name: Copy our code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run our test
      run: python test_app.py

  # --- THE CD PART (Package Docker & Simulate AWS EC2 Deployment) ---
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: test-code # 🛑 Wait until tests pass!
    
    steps:
    - name: Copy our code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Container Image
      run: docker build -t my-python-app:latest .

    - name: Connect to AWS EC2 & Deploy
      run: |
        echo "🔒 Securely authenticating with AWS using encrypted secrets..."
        echo "🌐 SSHing into EC2 Instance at IP Address [18.212.45.10]..."
        echo "📥 EC2 pulling latest Docker container from registry..."
        echo "🚀 Running container on EC2 port 80..."
        echo "🎉 SUCCESS! Your containerized app is live on AWS!"